#!/usr/bin/expect

# uncomment line below for debugging
# exp_internal 1

set timeout 7

spawn ./examples/optional


expect "{\"first_name\":\"Luke\",}\r\n{\"first_name\":\"Luke\",\"last_name\":null}\r\n{\"first_name\":\"Luke\",\"last_name\":null}\r\n{\"first_name\":\"Luke\",\"last_name\":\"Boswell\"}" {
    expect eof
    exit 0
}

puts stderr "\nError: output was different from expected value."
exit 1
